algorithm:
  type: PPO
environment:
  num_envs: 16
  frame_skip: 4
  frame_stack: 4
model:
  type: cnn
  hidden_dim: 512
ppo_hyperparameters:
  learning_rate: 2.5e-4
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
training:
  total_timesteps: 10000000
  n_steps: 128
  batch_size: 512
  n_epochs: 4
logging:
  tensorboard_log: ./logs/ppo
  seed: 42